### ISSUE TITLE
Specific element classnames

### ISSUE THREAD

**Issue by jshjohnson** [cferdinandi/gumshoe#15]
It would be ideal if, instead of applying the same class to both the list item and the link,  you could specify a class for each element - or only apply the class to one element.

Reason being, if you want active links to have a red background and the link has a border radius, you will loose the radius due to both elements inheriting the class! 

Great script by the way :)

**Comment by cferdinandi** [comment]
Just requires more specific CSS scoping. Example:

```css
a.active {
    background-color: red;
    border-radius: 4px;
}
```
