### ISSUE TITLE
Does not work correctly with: position: relative; height: 100vh;

### ISSUE THREAD

**Issue by cubooks** [cferdinandi/gumshoe#5]
Hi!

Sorry for my english, I'm from Russia. The problem is incorrect work with styles

```css
.element1 {
 position: relative;
 height: 100vh;
  .sub_element {
   position: absolute;
  }
}
```

Plugin begins to confuse the menu items and set the correct flag is not "active".

Screenshot: https://yadi.sk/i/XYvgkkuIeSPpR
