### ISSUE TITLE
Option to apply .active to parent <li> elements as well

### ISSUE THREAD

**Issue by archSeer** [cferdinandi/gumshoe#64]
On bootstrap's scrollspy, I added some styling that will automatically collapse any lists that are not currently active. The effect is that the menus automatically expand and collapse as we scroll.

```css
li:not(.active) > ul { display: none }
```

The difference is however, gumshoe only applies `.active` to the most lower level `<li>`. So if a second level navigation item becomes active, the entire menu collapses.

Would it be possible to have an option that also marks all of the parent `<li>` elements as active?

**Comment by cferdinandi** [comment]
Hey there. Not a feature in Gumshoe's core, but I think this could be bolted in [using the `callback` function](https://github.com/cferdinandi/gumshoe#global-settings).

Another note: for accessibility reasons, you shouldn't hide the menus with `display: none`. I would recommend doing this instead:

```css
li:not(.active) > ul {
	border: 0;
	clip: rect(0 0 0 0);
	height: 1px;
	margin: -1px;
	overflow: hidden;
	padding: 0;
	position: absolute;
	white-space: nowrap;
	width: 1px;
}
```

If you need help writing the actual callback function for this, please [reach out for Premium Support](https://gomakethings.com/support/).
